#!/usr/bin/env python3
"""
Posts an execution-summary comment to each case created by e2e_case_test.py.

Reads e2e_results.json, finds every 'ok' result, fetches the execution detail
from Kibana, and POSTs a formatted comment to the case with:
  - IOC inputs used
  - Execution ID + status
  - Step execution summary (total steps, any failures)
  - Workflow name + timestamp

Usage:
    export KIBANA_URL=...
    export KIBANA_API_KEY=...
    python3 post_execution_comments.py [--results e2e_results.json]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path
from datetime import datetime, timezone

KIBANA_URL = os.environ.get("KIBANA_URL", "").rstrip("/")
KIBANA_API_KEY = os.environ.get("KIBANA_API_KEY", "")

_MALICIOUS_IP = "185.220.101.47"
_USER = "jdoe@acmecorp.com"
_HOSTNAME = "DESKTOP-A4K9B2Z"
_SHA256 = "a3f8e2d1c9b4f7e6a5d2c8b1e9f4a7d3c6b2e5f8a1d4c7b3e6f2a9d5c8b4e7f1"


def _req(method: str, path: str, body: dict | None = None, timeout: int = 30):
    data = json.dumps(body).encode() if body is not None else None
    headers = {
        "kbn-xsrf": "true",
        "x-elastic-internal-origin": "Kibana",
        "Authorization": f"ApiKey {KIBANA_API_KEY}",
    }
    if data:
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(
        url=KIBANA_URL + path, method=method, headers=headers, data=data
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        return e.code, {"error": e.read().decode("utf-8", "replace")[:800]}
    except Exception as e:
        return 0, {"error": str(e)}


def get_execution(exec_id: str):
    status, body = _req("GET", f"/api/workflows/executions/{exec_id}")
    if status >= 400 or not isinstance(body, dict):
        return None
    return body


def build_comment(wf_result: dict, exec_body: dict | None) -> str:
    wf_title = wf_result.get("case_title", "Unknown workflow")
    exec_id = wf_result.get("exec_id", "")
    exec_status = wf_result.get("exec_status", "completed")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Step summary
    steps_total = 0
    steps_ok = 0
    steps_failed = 0
    steps_skipped = 0
    failed_step_names: list[str] = []

    if exec_body:
        step_execs = exec_body.get("stepExecutions") or []
        steps_total = len(step_execs)
        for s in step_execs:
            st = (s.get("status") or "").lower()
            if st == "completed":
                steps_ok += 1
            elif st in ("failed", "error"):
                steps_failed += 1
                failed_step_names.append(s.get("stepId", "?"))
            elif st in ("skipped", "cancelled"):
                steps_skipped += 1

    # Build step table rows for any failures
    failed_rows = ""
    if failed_step_names:
        failed_rows = "\n\n**Failed steps:**\n"
        for name in failed_step_names[:10]:
            failed_rows += f"- `{name}` — failed (on-failure: continue, execution proceeded)\n"

    step_summary = f"{steps_ok} completed"
    if steps_failed:
        step_summary += f", {steps_failed} failed (graceful)"
    if steps_skipped:
        step_summary += f", {steps_skipped} skipped"

    comment = f"""## Workflow Execution Report

**Tested at:** {now}
**Execution ID:** `{exec_id}`
**Execution status:** `{exec_status}`

---

### IOC Inputs Tested

| Field | Value |
|---|---|
| IP (C2/TOR exit) | `{_MALICIOUS_IP}` |
| User | `{_USER}` |
| Hostname | `{_HOSTNAME}` |
| SHA-256 (malware) | `{_SHA256[:32]}...` |
| Domain | `evil.example.com` |
| URL | `https://{_MALICIOUS_IP}/dropper/stage2.ps1` |
| Email subject | `ACTION REQUIRED: March Invoice` |
| Email sender | `hr-noreply@acmecorp-invoices.com` |

---

### Execution Summary

| Metric | Value |
|---|---|
| Total steps executed | {steps_total} |
| Steps completed | {steps_ok} |
| Steps failed (graceful) | {steps_failed} |
| Steps skipped | {steps_skipped} |
{failed_rows}
---

*Auto-generated by `e2e_case_test.py` — Elastic Kibana Workflows test harness*"""
    return comment


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="e2e_results.json")
    ap.add_argument("--sleep", type=float, default=0.4)
    ap.add_argument("--filter", default="", help="Only post to workflows whose path contains this")
    args = ap.parse_args()

    if not KIBANA_URL or not KIBANA_API_KEY:
        sys.stderr.write("Set KIBANA_URL and KIBANA_API_KEY.\n")
        return 2

    results = json.loads(Path(args.results).read_text())
    targets = [
        (p, r) for p, r in results.items()
        if r.get("result") == "ok" and args.filter in p
    ]

    print(f"Posting execution comments to {len(targets)} cases...")

    ok = 0
    fail = 0
    for idx, (yaml_path, wf_result) in enumerate(targets, 1):
        case_id = wf_result.get("case_id")
        exec_id = wf_result.get("exec_id")
        wf_title = wf_result.get("case_title", Path(yaml_path).stem)

        if not case_id:
            print(f"  [{idx}/{len(targets)}] SKIP  {Path(yaml_path).stem}  (no case_id)")
            continue

        # Fetch execution detail for step summary
        exec_body = get_execution(exec_id) if exec_id else None

        comment_text = build_comment(wf_result, exec_body)

        status, body = _req(
            "POST",
            f"/api/cases/{case_id}/comments",
            {
                "type": "user",
                "comment": comment_text,
                "owner": "securitySolution",
            },
        )

        if 200 <= status < 300:
            ok += 1
            print(f"  [{idx}/{len(targets)}] OK    {wf_title[:60]}")
        else:
            fail += 1
            err = (body.get("error") or str(body))[:120]
            print(f"  [{idx}/{len(targets)}] FAIL  {wf_title[:60]}  HTTP {status}: {err}")

        time.sleep(args.sleep)

    print(f"\nDone: {ok} posted, {fail} failed")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
