#!/usr/bin/env python3
"""
Triggers every imported workflow with a canned input payload and reports
pass/fail. Pairs with import_workflows.py — reads its imported.json
output mapping.

Usage:
    export KIBANA_URL="https://YOUR-DEPLOY.kb.REGION.PROVIDER.elastic-cloud.com"
    export KIBANA_API_KEY="<base64 id:api_key>"
    python3 run_workflows.py [--mapping imported.json] [--space default] [--out results.json]

Each workflow gets a generic input bundle (user, ip, url, hash, domain,
case_id, etc.). Most workflows ignore inputs they don't declare and Use
defaults; the rest will pull what they need from this bundle.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.request
import urllib.error
from pathlib import Path


CANNED_INPUTS = {
    "user": "mockuser@example.com",
    "users": ["alice@example.com", "bob@example.com"],
    "ip": "203.0.113.5",
    "ips": ["203.0.113.5", "198.51.100.10"],
    "url": "https://example.com/login",
    "urls": ["https://example.com/login", "https://example.com/dashboard"],
    "domain": "example.com",
    "domains": ["example.com", "evil.example.com"],
    "hash": "0" * 64,
    "hashes": ["0" * 64, "1" * 64],
    "file_hash_md5": "0" * 32,
    "file_hash_sha1": "0" * 40,
    "file_hash_sha256": "0" * 64,
    "device_id": "aid-mock-aaaa",
    "machine_id": "aid-mock-aaaa",
    "hostname": "mock-host-01",
    "kibana_case_id": "",
    "title": "Smoke-test ticket",
    "description": "Generated by run_workflows.py",
    "destination_address": "203.0.113.5",
    "destination_dns_domain": "example.com",
    "request_url": "https://example.com/login",
    "approve": False,
    "auto_approve": True,
    "dry_run": True,
    "response_choice": "",
}


def trigger(base_url: str, space: str, api_key: str, wf_id: str, inputs: dict):
    path = f"/s/{space}/api/workflows/{wf_id}/_execute" if space and space != "default" else f"/api/workflows/{wf_id}/_execute"
    req = urllib.request.Request(
        url=base_url.rstrip("/") + path,
        method="POST",
        headers={
            "kbn-xsrf": "true",
            "x-elastic-internal-origin": "Kibana",
            "Content-Type": "application/json",
            "Authorization": f"ApiKey {api_key}",
        },
        data=json.dumps({"inputs": inputs}).encode("utf-8"),
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            return resp.status, json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        return e.code, {"error": e.read().decode("utf-8", "replace")[:500]}
    except Exception as e:
        return 0, {"error": str(e)}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mapping", default="imported.json")
    ap.add_argument("--space", default="default")
    ap.add_argument("--out", default="results.json")
    ap.add_argument("--filter", default="", help="Only run workflows whose YAML path contains this substring")
    ap.add_argument("--sleep", type=float, default=0.2, help="Sleep between calls to be kind to Kibana")
    args = ap.parse_args()

    base = os.environ.get("KIBANA_URL")
    key = os.environ.get("KIBANA_API_KEY")
    if not base or not key:
        sys.stderr.write("Set KIBANA_URL and KIBANA_API_KEY env vars.\n")
        return 2

    mapping = json.loads(Path(args.mapping).read_text())
    targets = [(p, info["id"]) for p, info in mapping.items() if info.get("id") and (args.filter in p)]

    results = {}
    ok = 0
    fail = 0
    for path, wf_id in targets:
        status, body = trigger(base, args.space, key, wf_id, CANNED_INPUTS)
        if 200 <= status < 300:
            run_status = body.get("status") or body.get("data", {}).get("status") or "completed"
            print(f"ok    {path}  →  {run_status}")
            results[path] = {"status": status, "result": body}
            ok += 1
        else:
            err = body.get("error") if isinstance(body, dict) else body
            print(f"FAIL  {path}  ({status})  {str(err)[:200]}")
            results[path] = {"status": status, "error": err}
            fail += 1
        time.sleep(args.sleep)

    Path(args.out).write_text(json.dumps(results, indent=2))
    print(f"\n{ok}/{ok + fail} workflows completed (HTTP 2xx). Results in {args.out}.")
    return 0 if fail == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
